### ISSUE TITLE
[BUG]: docker部署Koishi安装插件找不到字体文件

### ISSUE THREAD

**Issue by Naexen** [DrLee-lihr/koishi-plugin-maimai#11]
2023-03-22 02:22:14 [W] market failed to parse koishi-plugin-maimai
2023-03-22 02:22:14 [W] market Error: ENOENT: no such file or directory, open '/koishi/node_modules/koishi-plugin-maimai\resources\FiraCode-Medium.ttf'
                            at Object.openSync (node:fs:601:3)
                            at Object.readFileSync (node:fs:469:35)
                            at Object.loadSync (/koishi/node_modules/opentype.js/dist/opentype.js:13854:22)
                            at Function.loadSync (/koishi/node_modules/text-to-svg/build/src/index.js:214:37)
                            at Object.<anonymous> (/koishi/node_modules/koishi-plugin-maimai/lib/mai_tool.js:15:42)
                            at Module._compile (node:internal/modules/cjs/loader:1254:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
                            at Module.load (node:internal/modules/cjs/loader:1117:32)
                            at Module._load (node:internal/modules/cjs/loader:958:12)
                            at Module.require (node:internal/modules/cjs/loader:1141:19)

**Comment by DrLee-lihr** [comment]
~~什么，这居然还有人用~~

字体文件是我直接放在 npm 包里的，如果缺失的话可以尝试一下重新装一下，或者直接下一个字体包（字体包内容正如文件名，`FiraCode-Medium`）放进对应路径

另外，目前作为高中牲学业繁忙，很难进行维护工作和及时回复 issues，请见谅。

**Comment by DrLee-lihr** [comment]
另外的话显然这个包已经多少年没有更新和适配 koishi 新版本了，如果不介意的话建议还是配合 koishi 旧版本用（  
而且这个包未来不保证继续维护，可能会闲置相当一段时间（可能到我高考结束），只建议暂时凑合用（）  
如有进一步问题或其他 bug ，仍然欢迎继续开 issue，我一定尽量利用空闲时间处理。

**Comment by Naexen** [comment]
OAO!高考加油！
